export const products = [
  {
    id: 1,
    name: "Joy",
    price: "399",
    description: "perfect when you want to express some joy.",
    image: "😂",
  },
  {
    id: 2,
    name: "Sob",
    price: "230",
    description: "when the funny is just too funny",
    image: "😭",
  },
  {
    id: 3,
    name: "Frog",
    price: "140",
    description: "a frog.",
    image: "🐸",
  },
  {
    id: 4,
    name: "Mad",
    price: "110",
    description: "for mad purposes.",
    image: "😠",
  },
  {
    id: 5,
    name: "Very Mad",
    price: "120",
    description: "grrrrr.",
    image: "😡",
  },
  {
    id: 6,
    name: "Smug Cat",
    price: "899",
    description: "this is one of the best.",
    image: "😼",
  },
  {
    id: 7,
    name: "Cool",
    price: "445",
    description: "cool guy.",
    image: "😎",
  },
  {
    id: 8,
    name: "Gango",
    price: "661",
    description: "don't know what to call this but it's cool",
    image: "🤙",
  },
  {
    id: 9,
    name: "Goat",
    price: "985",
    description: "my goat.",
    image: "🐐",
  },
  {
    id: 10,
    name: "Skull",
    price: "1",
    description: "just had to.",
    image: "💀",
  },
  {
    id: 11,
    name: "Nerd",
    price: "13",
    description: "erm actually.",
    image: "🤓",
  },
  {
    id: 12,
    name: "Pray",
    price: "333",
    description: "bless you.",
    image: "🙏",
  },
];
